### ISSUE TITLE
DbSettings is coming null

### ISSUE THREAD

**Issue by Guldaneoncul** [JuergenGutsch/blog#158]
Hi
I'm doing a service with a worker service. but it does not connect to the database. I use mongo as a database. When pulling the database settings it comes null.

Can you help me?

**Comment by JuergenGutsch** [comment]
Hi @Guldaneoncul 
Did you debug the worker service? Are you sure the connection string, etc. is available in the worker service.
Would be good to have some code, to have a look at. Otherwise, it will be hard to help :-)
Thanks
