### ISSUE TITLE
Broken link for "Integrate Meetup" example

### ISSUE THREAD

**Issue by benjaminpjones** [JuergenGutsch/blog#159]
https://asp.net-hacker.rocks/2017/03/13/integrate-meetup-events-on-your-website.html

The link I am talking about: [.NET User Group Nordwest-Schweiz](http://www.dotnet-nordwest.ch/)

I would love to see this in action before trying to use it in my own site!

**Comment by benjaminpjones** [comment]
Linking #68

**Comment by JuergenGutsch** [comment]
Hey @benjaminpjones 
The website is down, unfortunately. 
We completely moved to Meetup.

**Comment by benjaminpjones** [comment]
I am aware the website is down. I made this issue so you would know to update the blog post pointing to it accordingly.

https://www.github.com/JuergenGutsch/blog/tree/master/_source%2F_posts%2F2017-03-13-integrate-meetup-events-on-your-website.md
